### ISSUE TITLE
2018.9.

### ISSUE THREAD

**Issue by aplus1024** [aplus1024/iOS-Apps#1]
Hello, Minh~
This is A+.

**Comment by aplus1024** [comment]
Notification works?

**Comment by dalba1992** [comment]
Notification works?

**Comment by aplus1024** [comment]
Hi, A+
Nice to meet you here.

**Comment by aplus1024** [comment]
Hello, Minh
Nice!
Did you take the photo?
I want to chat with you on Skype today

**Comment by aplus1024** [comment]
Hi, A+
Let me know when you are available for live chatting.
Thanks

**Comment by aplus1024** [comment]
Hi, A+.
Hope you are well and your work goes well.
If we can have chat, I will be always online on skype.
Hope to hear from you soon.
Take care.

**Comment by aplus1024** [comment]
Hi, A+
How are you?
Mr Apple ask for research papers with structure sensor.
Hope to hear soon.
Warm regards.

**Comment by aplus1024** [comment]
Hello, Minh
Long time no see and I really hope to spend sweet chatting time with you on the Skype

But nowadays I am silly in our team because of no earning, so my whole body is burnning with submitting proposals from all possible job sites.
Moreover, next week, our building was sold and we move to another building
It's a very big work for our team

By the way, I will try to work on Apple's research paper about structure sensor.
But I forgot what kinds of paper he wanted because I sent him lots of paper last time, but he requested me different kinds of papers.
Please let me know the search keywords tomorrow morning so I can work tomorrow afternoon or night

How is your health? I see you must be making lots of effort in cold and severe environment.
Sending my warm regards
Always health first!

**Comment by aplus1024** [comment]
Hi Asharp,
I am Liu.
Long time no see.
I wish you earn much $$$.

Please help me.
I want to download following data.

https://www.dropbox.com/sh/u4g2o5kha0mt1uc/AADDMkoMKG2t4iiTxMUC6e2Ta?dl=0
https://drive.google.com/drive/folders/1QFZk_ED_FLW0xZC_gNuAKsYjLyKRMPPy

https://www.dropbox.com/sh/v754z1egib0hamh/AADGX1SE9GCj4h3eDazsc0bXa?dl=0
https://drive.google.com/open?id=168tC2OxS5DjyaiuDy_JhIV3eje8K_PLJ

I want you to download them asap.
Thanks.

**Comment by aplus1024** [comment]
Hi. Liu Hope you are well
I uploaded all
https://github.com/bciar/lab6
Thanks

**Comment by aplus1024** [comment]
Hi, A+
It's a pity that you can not have chat with me in skype.
Take care of yourself.
Health is first, as you said.
And apple requested research paper with structure sensor, not information about device.
Nothing special.
Download things you can find simply and upload them.
Then he will check and give you feedback. 
Take it easy.

Health is more precious than money.
Warm regards.

Minh.

**Comment by aplus1024** [comment]
Hello, Minh
Long time no see. We moved into the main company's building and settling down for life.
eating very poor, but life condition is good

I uploaded your tomcat and Apple's sensor research pdf together
Please tell him about my situation then he will understand. but please tell him for sure.

Please take care of your health always first
Warm Regards

**Comment by aplus1024** [comment]
Hi, A+.
Very GLAD hearing from you.
Hope you are well.
Downloaded all data, so you can remove them.
I'd love to have a chat with you in skype.
Hope to hear from you soon.
Take care.
Minh.

**Comment by aplus1024** [comment]
Please connect on Skype
mamosd1018
:)

**Comment by aplus1024** [comment]
Hi, A+

How are you?
I want you to download this app and send it to me.
https://play.google.com/store/apps/details?id=com.zmobileapps.xpress&hl=en_US
Warm regards.

Minh.

**Comment by aplus1024** [comment]
Hi
Please check $kype.

**Comment by aplus1024** [comment]
Hi, A+.

The messages on skype were from Mr. Cal.
It's unnecessary for me to ask you what you are doing.

BTW, this is our lab's requirement, lattest version of "Facefilter studio"

Take care of yourself, please.

Warm regards.

Minh.

**Comment by aplus1024** [comment]
Files are uploading for two days
Failed again and again, uploading again and again.
I cannot work anything others because uploading takes all bandwidth of my network
Anyway, I am trying continuously
1.13G
I never expected video can be uploaded to git
Will let you know once the uploading is finished

And any purchasing is forbidden here. Sorry about this.
Thanks.
